### PR TITLE
Add cleanup command

### PR DESCRIPTION
**Pull request by pierre**
* Fix issue where Tomcat PID wasn't properly detected
* Enhance README with high level description of commands (doesn't replace our documentation though, it's more like a quick reference for us)
* Add `kpm cleanup`

### CODE REVIEW

**Comment by pierre** [comment]
> fyi: Did not see where the tomcat PID detection fix was

Take a look at https://github.com/killbill/killbill-cloud/pull/155/commits/9a866052419fafd28b31601a383c45000e64cd0e#diff-095b4ef074cf133a3d35c965d55d1e34R275.

Basically:

```
2.4.1 :001 > foo
NameError: undefined local variable or method `foo' for main:Object
	from (irb):1
	from bin/irb:11:in `<main>'
2.4.1 :002 > def foo; puts('foo!'); end
 => :foo
2.4.1 :003 > foo
foo!
 => nil
2.4.1 :004 > foo = foo
 => nil
2.4.1 :005 > foo
 => nil
2.4.1 :006 > foo()
foo!
 => nil
```

Subtle...

**Comment by sbrossie** [comment]
But all i am seeing is that you renamed `apache_tomcat_pid` ->
`find_apache_tomcat_pid` and added a `@logger.debug` ?

**Comment by pierre** [comment]
> But all i am seeing is that you renamed `apache_tomcat_pid` -> `find_apache_tomcat_pid`

Exactly, the issue was:

```
apache_tomcat_pid = apache_tomcat_pid
```

Left is local variable assignment, right was supposed to be the method call.

**Comment by sbrossie** [comment]
> Exactly, the issue was:

> apache_tomcat_pid = apache_tomcat_pid
> Left is local variable assignment, right was supposed to be the method call.

Ah, got it 💡

**Pull request merged**
