### PR TITLE
Corrected incorrect syntax in docker-compose expose property

### PR DESCRIPTION
**Pull request by alibby**
docker-compose puked on "3306:3306" as expose is expected to be  'PORT[/PROTOCOL]'

### CODE REVIEW

**Comment by pierre** [comment]
This change does ring a bell, I thought we had the issue elsewhere (cc @sbrossie & @andrenpaes in case they remember).

Did the rest of the stack come up fine? The syntax is used [in other places](https://github.com/killbill/killbill-cloud/blob/master/docker/compose/docker-compose.gi.yml#L5-L8).

**Comment by sbrossie** [comment]
Based on [latest doc](https://docs.docker.com/compose/compose-file/) that seems valid, will merge

**Comment by pierre** [comment]
@sbrossie Shouldn't the same fix be applied [in other places](https://github.com/killbill/killbill-cloud/blob/master/docker/compose/docker-compose.gi.yml#L5-L8) too?

**Comment by sbrossie** [comment]
@pierre Indeed, just [fixed it](https://github.com/killbill/killbill-cloud/commit/570d513f2db5adbd0bd45677c307344599f4c58f)

**Pull request merged**
